name = "Adventure"
setup_guide = "https://archipelago.gg/tutorial/Adventure/setup_en"
home = "https://archipelago.gg"
supported = true
stability = "stable"
tracker = "https://github.com/ZobeePlays/Adventure-AP-Tracker"
