name = "APQuest"
setup_guide = "https://archipelago.gg/tutorial/APQuest/setup_en"
home = "https://archipelago.gg"
supported = true
stability = "stable"
tracker = "https://github.com/palex00/ap-quest-tracker/releases/latest"
