name = "Borderlands 2"
home = "https://github.com/EdricY/Bouncy-Loot-God"
default_url = "https://github.com/EdricY/Bouncy-Loot-God/releases/download/v{{version}}/borderlands2.apworld"
stability = "unstable"

[versions]
"be-85" = { url = "https://github.com/EdricY/Bouncy-Loot-God/releases/download/be-85/borderlands2.apworld" }
