name = "Celeste 64"
setup_guide = "https://archipelago.gg/tutorial/Celeste%2064/guide_en"
home = "https://archipelago.gg"
supported = true
stability = "stable"
tracker = "https://github.com/PoryGone/Celeste-64-AP-Tracker/releases/latest"
