name = "Chests 'n' Keys"
home = "https://github.com/not-aoyama/ChestsNKeys-Web"

[versions]
"0.3.0" = { url = "https://github.com/not-aoyama/ChestsNKeys-Web/releases/download/v0.3.0/chests_n_keys.apworld" }
