name = "Civilization VI"
setup_guide = "https://archipelago.gg/tutorial/Civilization%20VI/setup_en"
home = "https://archipelago.gg"
supported = true
stability = "stable"
tracker = "https://github.com/Gearwcu/CivVI-poptracker-pack/releases/latest"
