name = "Crash Bandicoot 2: Cortex Strikes Back"
home = "https://github.com/Sim10XXX/C2AP"
default_url = "https://github.com/Sim10XXX/C2AP/releases/download/v{{version}}/crash2.apworld"
stability = "unstable"
setup_guide = "https://github.com/Sim10XXX/C2AP/blob/master/README.md"

[versions]
"0.3.0" = {}
