name = "Cvaos"
home = "https://github.com/anonymous-heap/Archipelago"
stability = "untested"

[versions]
"2026.7.3.post2" = { url = "https://github.com/anonymous-heap/Archipelago/releases/download/cvaos-apworld-2026.07.13/cvaos.apworld" }
