name = "Deaths Door"
home = "https://github.com/roseasromeo/DeathsDoorAPWorld"
default_url = "https://github.com/roseasromeo/DeathsDoorAPWorld/releases/download/v{{version}}/deaths_door.apworld"
stability = "untested"

[versions]
"0.2.1" = {}
