name = "Donkey Kong 64"
home = "https://discord.com/channels/731205301247803413/1409624528912650360"
default_url = "https://github.com/2dos/DK64-Randomizer-Release/releases/download/v{{version}}/dk64.apworld"
disabled=true
stability = "stable"
setup_guide = "https://github.com/2dos/DK64-Randomizer/wiki/Archipelago-Dev-Setup-Guide"

[versions]
"1.0.55" = {}
"1.5.1" = {}
