name = "DLCQuest"
setup_guide = "https://archipelago.gg/tutorial/DLCQuest/setup_en"
home = "https://archipelago.gg"
supported = true
stability = "stable"
tracker = "https://github.com/RaceProUK/DLCQuest-APTracker/releases/latest"
