name = "DOOM II"
setup_guide = "https://archipelago.gg/tutorial/DOOM%20II/setup_en"
home = "https://archipelago.gg"
supported = true
stability = "stable"
tracker = "https://github.com/Ozone31/doomii-ap-tracker/releases/latest"
