name = "Dragon Quest Monsters 2"
home = "https://github.com/Whizzlefern/Archipelago"

[versions]
"dqm2-v0.1.1" = { url = "https://github.com/Whizzlefern/Archipelago/releases/download/dqm2-v0.1.1/dqm2.apworld" }
