name = "Etrian Odyssey"
home = "https://github.com/TheMasterZelda/Etrian_Odyssey_1_Archipelago"
default_url = "https://github.com/TheMasterZelda/Etrian_Odyssey_1_Archipelago/releases/download/v{{version}}/etrian_odyssey.apworld"
stability = "untested"

[versions]
"0.4.1" = {}
