name = "Everhood 2"
home = "https://github.com/DeamonHunter/ArchipelagoEverhood2"
default_url = "https://github.com/DeamonHunter/ArchipelagoEverhood2/releases/download/v{{version}}/everhood_2.apworld"
stability = "untested"

[versions]
"0.4.8" = {}

[[fuzz_results]]
version = "0.4.8"
verdict = "broken"
fuzzed_at = "2026-08-29"
seeds = 2504
default_rate = 0.34385
worst_hook = "check-ut"
worst_hook_rate = 0.354478
