name = "Factorio Bob's"
home = "https://github.com/Osiris32-and-a-half/BobFactorioAP"

[versions]
"2.2.6" = { url = "https://github.com/Osiris32-and-a-half/BobFactorioAP/releases/download/V2.2.6/factorio_bobs.apworld" }
