name = "Fakutori"
home = "https://github.com/chickentuna/Archipelago-Fakutori"
stability = "untested"

[versions]
"1.0.0" = { url = "https://github.com/chickentuna/Archipelago-Fakutori/releases/download/v0.1.0/fakutori.apworld" }
