name = "Fantastic Fist"
home = "https://github.com/DannySchultzDev/Fantastic-Fist-Archipelago-Client"
stability = "untested"

[versions]
"0.0.1" = { url = "https://github.com/DannySchultzDev/Fantastic-Fist-Archipelago-Client/releases/download/V0.0.2/fantastic_fist.apworld" }
