name = "Final Fantasy Crystal Chronicles"
home = "https://github.com/EverydaySimpleDev/Archipelago"

[versions]
"ffcc-beta.0.0.1" = { url = "https://github.com/EverydaySimpleDev/Archipelago/releases/download/ffcc-beta.0.0.1/ffcc.apworld" }
