name = "Final Fantasy V Career Day"
home = "https://github.com/junglechief87/arch_ffvcd"
stability = "untested"

[versions]
"83.1" = { url = "https://github.com/junglechief87/arch_ffvcd/releases/download/v83.1/ffvcd.apworld" }
