name = "Flipwitch"
home = "https://github.com/Witchybun/FlipwitchAPClient"
default_url = "https://github.com/Witchybun/FlipwitchAPClient/releases/download/{{version}}/flipwitch.apworld"
stability = "stable"

[versions]
