name = "Huniepop"
home = "https://github.com/DotsofdarknessArchipelago/HuniePopArchipelago"
default_url = "https://github.com/DotsofdarknessArchipelago/HuniePopArchipelago/releases/download/{{version}}/huniepop.apworld"
stability = "stable"

[versions]
