name = "Hylics 2"
setup_guide = "https://archipelago.gg/tutorial/Hylics%202/setup_en"
home = "https://archipelago.gg"
supported = true
stability = "stable"
tracker = "https://github.com/superfid2006/Hylics2-poptracker/releases/latest"
