name = "Kirby Super Star"
home = "https://discord.com/channels/731205301247803413/1455078199611490384"
default_url = "https://github.com/Silvris/Archipelago/releases/download/kss_{{version}}/kss.apworld"
stability = "stable"
tracker = "https://github.com/Talcerase/kss-ap-poptracker/releases/latest"

[versions]
"0.0.4" = {}
"0.1.1" = {}
"0.1.2" = {}
"0.1.4" = {}
"0.1.6" = {}
"0.1.7" = {}
"0.1.9" = {}
