name = "Loonyland: Halloween Hill"
home = "https://github.com/AutomaticFrenzy/Archipelago"
default_url = "https://github.com/AutomaticFrenzy/Archipelago/releases/download/v{{version}}/loonyland.apworld"
stability = "stable"

[versions]
"0.2.1" = {}
