name = "Luck be a Landlord"
home = "https://github.com/Littlemuzz5/Luck-Be-a-Landlord-AP"

[versions]
"Luck_be_a_Landlord_beta_2" = { url = "https://github.com/Littlemuzz5/Luck-Be-a-Landlord-AP/releases/download/Luck_be_a_Landlord_beta_2/luck_be_a_landlord.apworld" }
