name = "Manual_WatchAShow_Chakraa"
home = "https://github.com/ChakraaThePanda/Archipelago-Manual-WatchAShow"

[versions]
"2026.09.12" = { url = "https://github.com/ChakraaThePanda/Archipelago-Manual-WatchAShow/releases/download/2026.09.12/manual_watchashow_chakraa.apworld" }
