name = "Manual_DbDSurvEN_Wabadjakk"
home = "https://github.com/Wabadjakk/AP_manual_DbDSurv"

[versions]
".1.1.4" = { url = "https://github.com/Wabadjakk/AP_manual_DbDSurv/releases/download/V.1.1.4/manual_dbdsurven_wabadjakk.apworld" }
