name = "manual_mhrise_village_axxroy"
home = "https://github.com/axxroytovu/archipelago_manuals"

[versions]
"Rise_1.0.0" = { url = "https://github.com/axxroytovu/archipelago_manuals/releases/download/Rise_1.0.0/manual_mhrise_village_axxroy.apworld" }
