name = "Manual_mp9v2_squidy"
home = "https://github.com/Joethepic/Archipelago"

[versions]
"2.0mp9" = { url = "https://github.com/Joethepic/Archipelago/releases/download/2.0mp9/manual_mp9v2_squidy.apworld" }
