name = "Manual_TooManyNights_WolfBoi008"
display_name = "Manual: TOO MANY NIGHTS"
home = "https://github.com/WolfBoi008/Too-Many-Nights/tree/main"

[versions]
"2.1.0+a" = { url = "https://github.com/WolfBoi008/Too-Many-Nights/releases/download/2.1.0a/manual_toomanynights_wolfboi008.apworld" }
"2.1.0b" = { url = "https://github.com/WolfBoi008/Too-Many-Nights/releases/download/2.1.0b/manual_toomanynights_wolfboi008.apworld" }
"2.1.1" = { url = "https://github.com/WolfBoi008/Too-Many-Nights/releases/download/2.1.1/manual_toomanynights_wolfboi008.apworld" }
