name = "Manual: Captain Toad: Treasure Tracker"
home = "https://github.com/smashebrada/Captain-Toad-Treasure-Tracker-Manual-apworld"

[versions]
"1.0.3" = { url = "https://github.com/smashebrada/Captain-Toad-Treasure-Tracker-Manual-apworld/releases/download/archipelago/manual_captaintoadtreasuretracker_smashebrada.apworld" }
