name = "Mario Sports Mix"
home = "https://github.com/ElectroStarz/ArchipelagoMSM"

[versions]
"3.0.0" = { url = "https://github.com/ElectroStarz/ArchipelagoMSM/releases/download/v3.0.0/mario_sports_mix.apworld" }
