name = "The Messenger"
setup_guide = "https://archipelago.gg/tutorial/The%20Messenger/setup_en"
home = "https://archipelago.gg"
supported = true
stability = "stable"
tracker = "https://github.com/alwaysintreble/TheMessengerTrackPack/releases/latest"
