name = "Mega Man 2"
setup_guide = "https://archipelago.gg/tutorial/Mega%20Man%202/setup_en"
home = "https://archipelago.gg"
supported = true
stability = "stable"
tracker = "https://github.com/BrianCumminger/megaman2-ap-poptracker/releases/latest"
