name = "Noita"
setup_guide = "https://archipelago.gg/tutorial/Noita/setup_en"
home = "https://archipelago.gg"
supported = true
stability = "stable"
tracker = "https://github.com/ScipioWright/Noita-poptracker/releases/latest"
