name = "Northgard"
home = "https://github.com/ChakraaThePanda/Archipelago-Northgard"

[versions]
"2026.09.14" = { url = "https://github.com/ChakraaThePanda/Archipelago-Northgard/releases/download/2026.09.14/northgard.apworld" }
