name = "Return of the Obra Dinn"
home = "https://github.com/wkcheezy/ObraDinnArchipelagoWorld"
default_url = "https://github.com/wkcheezy/ObraDinnArchipelagoWorld/releases/download/v{{version}}/obra_dinn.apworld"
stability = "untested"

[versions]
"0.0.2" = {}
