name = "Oxygen Not Included"
home = "https://github.com/ShadowKitty42/ONI-Archipelago"
default_url = "https://github.com/ShadowKitty42/ONI-Archipelago/releases/download/v{{version}}/oni.apworld"
stability = "stable"

[versions]
