name = "Peggle Deluxe"
home = "https://discord.com/channels/731205301247803413/1470246861557334016"
default_url = "https://github.com/SerpentAI/Archipelago/releases/download/peggle-deluxe-v{{version}}/peggle_deluxe.apworld"
stability = "stable"

[versions]
"1.2.0" = { url = "https://github.com/SerpentAI/Archipelago/releases/download/peggle-deluxe-v1.2.0/peggle_deluxe.apworld" }