name = "Plok"
home = "https://github.com/Happyhappyism/Plok-Archipelago"

[versions]
"0.1.2" = { url = "https://github.com/Happyhappyism/Plok-Archipelago/releases/download/plok_v0.1.3/plok.apworld" }
