name = "Ratchet & Clank"
home = "https://discord.com/channels/731205301247803413/1146024297324879872"
default_url = "https://github.com/Panda291/Archipelago/releases/download/v{{version}}/rac1.apworld"
stability = "unstable"
setup_guide = "https://boltcrate.space/#:~:text=Ratchet%20%26%20Clank%20Archipelago"
tracker = "https://github.com/SomeLazyGamer/RaC-5-SM-AP-Poptracker/releases"

[versions]
"0.1.3" = {}
