name = "Risk of Rain 2"
setup_guide = "https://archipelago.gg/tutorial/Risk%20of%20Rain%202/setup_en"
home = "https://archipelago.gg"
supported = true
stability = "stable"
tracker = "https://github.com/Swiftmane/Ror2-AP-tracker/releases/latest"
