name = "Sayonara Wild Hearts"
home = "https://github.com/Chainsawkitten/SayonaraWildHeartsAP"

[versions]
"1.0.0" = { url = "https://github.com/Chainsawkitten/SayonaraWildHeartsAP/releases/download/1.0.0/sayonarawildhearts.apworld" }
