name = "Secret Agent Clank"
home = "https://github.com/Panguu/Archipelago-RaCSM"

[versions]
"0.0.1" = { url = "https://github.com/Panguu/Archipelago-RaCSM/releases/download/secret-agent-clank/v0.0.1/secret_agent_clank.apworld" }
