name = "Shadowgate 64"
home = "https://github.com/jjjj12212/Archipelago-Shadowgate64"

[versions]
"0.1" = { url = "https://github.com/jjjj12212/Archipelago-Shadowgate64/releases/download/V0.1/shadowgate64.apworld" }
