name = "Hollow Knight: Silksong"
home = "https://github.com/Batatvideogames/silksong-archipelago-randomizer"

[versions]
"0.4.5-Hotfix2" = { url = "https://github.com/Batatvideogames/silksong-archipelago-randomizer/releases/download/v0.4.5-Hotfix2/silksong.apworld" }
