name = "Secret of Evermore"
setup_guide = "https://archipelago.gg/tutorial/Secret%20of%20Evermore/multiworld_en"
home = "https://archipelago.gg"
supported = true
stability = "stable"
tracker = "https://github.com/Cyb3RGER/evermizer-tracker-package/releases/latest"
