name = "ActRaiser"
home = "https://github.com/Happyhappyism/Archipelago"
default_url = "https://github.com/Happyhappyism/Archipelago/releases/download/{{version}}/sonic_battle.apworld"
stability = "stable"

[versions]
"sonic_battle_v0.1.3" = {}
