name = "Sentinels of the Multiverse"
home = "https://github.com/Totox00/Archipelago-sotm"
default_url = "https://github.com/Totox00/Archipelago-sotm/releases/download/v{{version}}/sotm.apworld"
stability = "stable"
setup_guide = "https://github.com/Totox00/Archipelago-sotm/blob/main/worlds/sotm/docs/setup_en.md"

[versions]
"0.4.5" = {}
