name = "Spirit Valley"
home = "https://github.com/DotsofdarknessArchipelago/Spirit-Valley-Archipelago"
default_url = "https://github.com/DotsofdarknessArchipelago/Spirit-Valley-Archipelago/releases/download/{{version}}/spiritvalley.apworld"
stability = "unstable"

[versions]
"2.0.0" = { url = "https://github.com/DotsofdarknessArchipelago/Spirit-Valley-Archipelago/releases/download/V2.0.0/spiritvalley.apworld" }
