name = "The Legend of Spyro: Dawn of the Dragon"
home = "https://github.com/IcyPenguin28/DotDAP"

[versions]
"0.2.0" = { url = "https://github.com/IcyPenguin28/DotDAP/releases/download/0.2.0/spyro_dotd.apworld" }
