name = "Terra Nil"
home = "https://github.com/nepcore/TerraNilAP"
default_url = "https://github.com/nepcore/TerraNilAP/releases/download/v{{version}}/TerraNil.apworld"
stability = "unstable"

[versions]
"0.2.0" = {}
"0.2.1-pre4" = {}
"0.2.1" = {}
