name = "Touhou Youyoumu ~ Perfect Cherry Blossom"
home = "https://discord.com/channels/1085716850370957462/1368333426142216342"
default_url = "https://github.com/Nepley/pcb-apworld/releases/download/v{{version}}/th07.apworld"
tags = ["ad"]
stability = "stable"
tracker = "https://github.com/Nepley/pcb-poptracker/releases"

[versions]
"1.1.2" = {}
"1.1.4" = {}
"1.2.2" = {}
"1.2.3" = {}

[[fuzz_results]]
version = "1.2.3"
verdict = "flaky"
fuzzed_at = "2026-09-08"
seeds = 5000
default_rate = 0.0276
worst_hook = "default"
worst_hook_rate = 0.0276
