name = "ToeJam and Earl"
home = "https://discord.com/channels/731205301247803413/1204326236415856671"
default_url = "https://github.com/IgnisUmbrae/TJE-Archipelago/releases/download/v{{version}}/tje.apworld"
disabled = true # 2% failure rate

[versions]
"0.3.1" = { url = "https://github.com/IgnisUmbrae/TJE-Archipelago/releases/download/v0.3.1/tje.apworld" }
"0.3.2" = {}
"0.5.4" = {}

[versions."0.5.4".fuzz_result]
verdict = "broken"
default_rate = 0.05
worst_hook = "check-collect-accessibility"
worst_hook_rate = 0.225738
seeds = 5000
fuzzed_at = "2026-05-13"
