name = "Toy Story 2"
home = "https://github.com/imklubb/Archipelago-Toy-Story-2"

[versions]
"2.2.0" = { url = "https://github.com/imklubb/Archipelago-Toy-Story-2/releases/download/2.3.1/toystory2.apworld" }
