name = "UNBEATABLE Arcade"
home = "https://discord.com/channels/731205301247803413/1454317500329099317"
default_url = "https://github.com/AllPoland/unbeatAP/releases/download/v{{version}}/unbeatable_arcade.apworld"

[versions]
"0.1.0-alpha" = { }
"0.2.1-alpha" = { }
"0.3.0-alpha" = {}
"0.4.0-alpha" = {}

[versions."0.4.0-alpha".fuzz_result]
verdict = "broken"
default_rate = 0.500851
worst_hook = "default"
worst_hook_rate = 0.500851
seeds = 4702
fuzzed_at = "2026-05-13"
