name = "Unfair Flips"
home = "https://discord.com/channels/731205301247803413/1460737685151940819"
default_url = "https://github.com/xMcacutt-Archipelago/Archipelago-UnfairFlips/releases/download/{{version}}/unfair_flips.apworld"
stability = "stable"
tracker = "https://github.com/lighting8282/Unfair-Flips-PopTracker/releases/tag/v0.0.3"

[versions]
"1.0.4" = {}
"1.1.0" = {}
"1.2.0" = {}
"1.2.1" = {}
