name = "Vespadian"
home = "https://github.com/Quinn-Patrick/Archipelago-Vespadian"
default_url = "https://github.com/Quinn-Patrick/Archipelago-Vespadian/releases/download/V{{version}}/vespadian.apworld"
stability = "unstable"

[versions]
"0.1.1" = {}
"V0.1.1" = { url = "https://github.com/Quinn-Patrick/Archipelago-Vespadian/releases/download/V0.1.1/vespadian.apworld" }
