name = "The Witness"
setup_guide = "https://archipelago.gg/tutorial/The%20Witness/setup_en"
home = "https://archipelago.gg"
supported = true
stability = "stable"
tracker = "https://github.com/NewSoupVi/witness_archipelago_tracker/releases/latest"
