name = "Yakuza Gaiden"
home = "https://github.com/zorasknight/YakLaDGaiRando"

[versions]
"Beta2r2" = { url = "https://github.com/zorasknight/YakLaDGaiRando/releases/download/Beta2/yakuza_gaiden.apworld" }
