name = "Zillion"
setup_guide = "https://archipelago.gg/tutorial/Zillion/setup_en"
home = "https://archipelago.gg"
supported = true
stability = "stable"
tracker = "https://github.com/Br00ty/zillion_brooty/releases/latest"
